name: Cypress Tests with Mochawesome Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm run test

      - name: Merge Mochawesome Reports
        run: npm run merge-report

      - name: Generate HTML Report
        run: npm run generate-report

      - name: Upload Mochawesome Report
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: cypress/reports/html
